import type { Flight, Hotel, Car, Guide } from "./types";

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: "f1",
    airline: "Kenya Airways",
    flightNumber: "KQ470",
    origin: "Nairobi",
    destination: "Kigali",
    departureTime: "10:30 AM",
    arrivalTime: "12:15 PM",
    duration: "1h 45m",
    stops: "Direct",
    price: 450,
  },
  {
    id: "f2",
    airline: "Ethiopian Airlines",
    flightNumber: "ET308",
    origin: "Addis Ababa",
    destination: "Kigali",
    departureTime: "2:00 PM",
    arrivalTime: "3:30 PM",
    duration: "1h 30m",
    stops: "Direct",
    price: 520,
  },
  {
    id: "f3",
    airline: "RwandAir",
    flightNumber: "WB204",
    origin: "Johannesburg",
    destination: "Kigali",
    departureTime: "8:00 AM",
    arrivalTime: "1:30 PM",
    duration: "5h 30m",
    stops: "1 stop",
    price: 680,
  },
];

export const MOCK_HOTELS: Hotel[] = [
  {
    id: "h1",
    name: "Kigali Serena Hotel",
    address: "City Center, Kigali",
    stars: 5,
    pricePerNight: 180,
    amenities: ["WiFi", "Pool", "Restaurant", "Gym", "Spa"],
    rating: 4.8,
  },
  {
    id: "h2",
    name: "Radisson Blu Hotel",
    address: "Near Airport, Kigali",
    stars: 4,
    pricePerNight: 120,
    amenities: ["WiFi", "Gym", "Bar", "Parking"],
    rating: 4.5,
  },
  {
    id: "h3",
    name: "Marriott Hotel Kigali",
    address: "City Center, Kigali",
    stars: 5,
    pricePerNight: 200,
    amenities: ["WiFi", "Pool", "Restaurant", "Spa", "Business Center"],
    rating: 4.9,
  },
  {
    id: "h4",
    name: "Park Inn by Radisson",
    address: "City Center, Kigali",
    stars: 3,
    pricePerNight: 95,
    amenities: ["WiFi", "Restaurant", "Bar"],
    rating: 4.2,
  },
  {
    id: "h5",
    name: "Heaven Boutique Hotel",
    address: "Kiyovu, Kigali",
    stars: 4,
    pricePerNight: 140,
    amenities: ["WiFi", "Restaurant", "Garden", "Rooftop Bar"],
    rating: 4.6,
  },
  {
    id: "h6",
    name: "The Retreat by Heaven",
    address: "Nyarutarama, Kigali",
    stars: 5,
    pricePerNight: 220,
    amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Butler Service"],
    rating: 4.9,
  },
];

export const MOCK_CARS: Car[] = [
  {
    id: "c1",
    model: "Toyota Corolla",
    category: "sedan",
    pricePerDay: 45,
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    features: ["A/C", "Bluetooth", "USB"],
  },
  {
    id: "c2",
    model: "Toyota RAV4",
    category: "suv",
    pricePerDay: 85,
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    features: ["4WD", "A/C", "GPS", "Premium Sound"],
  },
  {
    id: "c3",
    model: "Toyota Hiace",
    category: "van",
    pricePerDay: 120,
    seats: 9,
    transmission: "Manual",
    fuelType: "Diesel",
    features: ["A/C", "Large Storage", "USB Charging"],
  },
  {
    id: "c4",
    model: "Honda CR-V",
    category: "suv",
    pricePerDay: 90,
    seats: 5,
    transmission: "Automatic",
    fuelType: "Hybrid",
    features: ["4WD", "A/C", "Bluetooth", "Safety Pack"],
  },
  {
    id: "c5",
    model: "Land Cruiser Prado",
    category: "suv",
    pricePerDay: 150,
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    features: ["4WD", "A/C", "GPS", "Premium Leather"],
  },
  {
    id: "c6",
    model: "Mercedes Vito",
    category: "van",
    pricePerDay: 180,
    seats: 8,
    transmission: "Automatic",
    fuelType: "Diesel",
    features: ["A/C", "WiFi", "USB", "Premium Interior"],
  },
];

export const MOCK_GUIDES: Guide[] = [
  {
    id: "g1",
    type: "Full-Day Guide",
    description: "8 hours of expert guidance",
    price: 100,
    languages: ["English", "French", "Kinyarwanda"],
  },
  {
    id: "g2",
    type: "Half-Day Guide",
    description: "4 hours for specific sites",
    price: 60,
    languages: ["English", "French"],
  },
  {
    id: "g3",
    type: "Safari Specialist",
    description: "Expert wildlife & nature guide",
    price: 150,
    languages: ["English", "French", "German"],
  },
];

export const DRIVER_SURCHARGE = 35;
export const SERVICE_FEE_RATE = 0.05;
export const ITEMS_PER_PAGE = 4;
